# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install && npm run client-install
    curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
    chmod +x ./snyk
    mv ./snyk /usr/local/bin/
    npm install snyk-to-html -g
    mkdir -p results
    snyk auth $(SNYK_TOKEN)
    snyk test --all-projects
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)
  displayName: 'Security Scan'


   